name: CI/CD

on:
  push:
    branches:
      - deploy/ec2  # Corrected branch name for trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t sarujansk/react-new-project-app .

      - name: Push Docker Image
        run: docker push sarujansk/react-new-project-app:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Use self-hosted runner
    steps:
      - name: Pull Image From Docker Hub
        run: docker pull sarujansk/react-new-project-app:latest

      - name: Delete Old Container
        run: docker rm -f reactContainer || true  # Ignore error if container does not exist

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactContainer sarujansk/react-new-project-app

# Sk Sharu